### ISSUE TITLE
BoxDecoration not working?

### ISSUE THREAD

**Issue by doanbh** [ethanblake4/flutter_eval#31]
I'm use:
`decoration: BoxDecoration(
                              color: Colors.red,
                              shape: BoxShape.circle
                          ),`
[https://ibb.co/71NR0mD](url)

///
The following CompileError was thrown building EvalWidget(dirty, state: _EvalWidgetState#acbe1):
Cannot assign argument of type BoxDecoration to parameter of type Decoration at unknown (file package:example/main.dart)

**Comment by canewsin** [comment]
@doanbh 
some args might be missing, I see such error might occur when certain args are missing. Try adding `boxShadow` val.
https://github.com/ethanblake4/flutter_eval/blob/055203e17f57c6484696f6826628200cdf8a0dc1/lib/src/painting/box_decoration.dart#L35-L45

**Comment by ethanblake4** [comment]
Fixed in v0.6.0

**Comment by nguyendangkhoi** [comment]
still not working in v0.6.0, still not support borderRadius and shape
     //image: args[1]?.value as DecorationImage?, 
     //borderRadius: args[3]?.value as BorderRadius?, 
     //gradient: args[5]?.value as Gradient?, 
     //backgroundBlendMode: args[6]?.value as BlendMode?, 
     //shape: args[7]?.value as BoxShape?
